import door
import time

def insane():
    print("(You enter a room with a car parked. A door shuts behind you.)")
    print("But Stanley just couldn't do it.")
    time.sleep(1)
    print("He considered the possibility of facing his boss, admitting he had left his post during work hours, he might be fired for that. And in such a competitive economy, why had he taken that risk?")
    time.sleep(8)
    print("(You enter a room with a series of clocks and filing droors.)")
    print("All because he believed everyone had vanished? His boss would think he was crazy.")
    time.sleep(2)
    print("And then something occurred to Stanley: Maybe, he thought to himself, maybe I am crazy. All of my coworkers blinking mysteriously out of existence in a single moment for no reason at all?")
    time.sleep(8)
    print("(You enter a dull room with a vending machine.)")
    print("None of it made any logical sense. And as Stanley pondered this he began to make other strange observations.")
    time.sleep(3)
    print("(You enter a room with a car parked.)")
    print("For example, why couldn't he see his feet when he looked down? Why did doors close automatically behind him wherever he went?")
    time.sleep(5)
    print("(You enter a room with a series of clocks and filing droors.)")
    print("And for that matter, these rooms were starting to look pretty familiar, were they simply repeating?")
    time.sleep(4)
    print("No, Stanley said to himself, this is all too strange, this can't be real, and at last he came to the conclusion that had been on the tip of his tongue, he just hadn't found the words for it.")
    time.sleep(7)
    print("(You no longer seem to care about the rooms.)")
    print("I'm dreaming! he yelled, This is all a dream!")
    time.sleep(1)
    print("What a relief Stanley felt to have finally found an answer, an explanation. His coworkers weren't actually gone, he wasn't going to lose his job, he wasn't crazy after all!")
    time.sleep(6)
    print("And he thought to himself, I suppose I'll wake up soon, I'll have to go back to my boring real life job pushing buttons, I may as well enjoy this while i'm still lucid.")
    time.sleep(6)
    print("So he imagined himself flying, and began to gently float above the ground.")
    time.sleep(4)
    print("Then he imagined himself soaring through space on a magical star field, and it too appeared!")
    time.sleep(4)
    print("It was so much fun, and Stanley marveled that he had still not woken up. How was he remaining so lucid?")
    time.sleep(5)
    print("And then perhaps the strangest question of them all entered Stanley's head, one he was amazed he hadn't asked himself sooner:")
    time.sleep(5)
    print("Why is there a voice in my head, dictating everything that i'm doing and thinking?")
    time.sleep(3)
    print("Now the voice was describing itself being considered by Stanley, who found it particularly strange. I'm dreaming about a voice describing me thinking about how it's describing my thoughts, he thought!")
    time.sleep(7)
    print("And while he thought it all very odd and wondered if this voice spoke to all people in their dreams, the truth was that of course this was not a dream. How could it be?")
    time.sleep(6)
    print("Was Stanley simply deceiving himself? Believing that if he's asleep he doesn't have to take responsibility for himself?")
    time.sleep(5)
    print("Stanley is as awake right now as he's ever been in his life.")
    time.sleep(3)
    print("Now hearing the voice speak these words was quite a shock to Stanley. After all, he knew for certain beyond a doubt that this was, in fact, a dream!")
    time.sleep(5)
    print("Did the voice not see him float and make the magical stars just a moment ago? How else would the voice explain all that?")
    time.sleep(5)
    print("This voice was a part of himself too, surely, surely if he could just....")
    time.sleep(3)
    print("He would prove it. He would prove that he was in control, that this was a dream.")
    time.sleep(3)
    print("So he closed his eyes gently, and he invited himself to wake up.")
    time.sleep(2)
    print("(You close your eyes.)")
    time.sleep(2)
    print("He felt the cool weight of the blanket on his skin, the press of the mattress on his back,")
    time.sleep(3)
    print("the fresh air of a world outside this one. Let me wake up, he thought to himself.")
    time.sleep(3)
    print("I'm through with this dream, I wish it to be over. Let me go back to my job, let me continue pushing the buttons, please, it's all I want.")
    time.sleep(6)
    print("I want my apartment, and my wife, and my job. All I want is my life exactly the way it's always been.")
    time.sleep(4)
    print("My life is normal, I am normal. Everything will be fine.")
    time.sleep(3)
    print("I am okay.")
    time.sleep(5)
    print("(You open your eyes, and see a parked car.)")
    print("Stanley began screaming.")
    time.sleep(1)
    print("Please someone wake me up!")
    time.sleep(0.5)
    print("My name is Stanley!")
    time.sleep(0.5)
    print("I have a boss!")
    time.sleep(0.5)
    print("I have an office! I am real!")
    time.sleep(0.5)
    print("(The world grows red around you.)")
    print("Please just someone tell me i'm real!")
    time.sleep(1)
    print("I must be real! I must be!")
    time.sleep(0.5)
    print("Can anyone hear my voice?!")
    time.sleep(0.5)
    print("Who am I?!")
    time.sleep(0.5)
    print("WHO AM I?!")
    time.sleep(1)
    print("And everything went black.")
    print()
    time.sleep(5)
    print("This is the story of a woman named Mariella.")
    time.sleep(3)
    print("Mariella woke up on a day like any other. She arose, got dressed, gathered her belongings, and walked to her place of work.")
    time.sleep(5)
    print("But on this particular day, her walk was interrupted by the body of a man who had stumbled through town talking and screaming to himself and then collapsed dead on the sidewalk.")
    time.sleep(7)
    print("And although she would soon turn to go call for an ambulance, for just a few, brief moments, she considered the strange man.")
    time.sleep(5)
    print("He was obviously crazy; this much she knew. Everyone knows what crazy people look like.")
    time.sleep(3)
    print("And in that moment, she thought to herself how lucky she was to be normal.")
    time.sleep(3)
    print("I am sane. I am in control of my mind. I know what is real, and what isn't.")
    time.sleep(3)
    print("It was comforting to think this, and in a certain way, seeing this man made her feel better. But then she remembered the meeting she had scheduled for that day,")
    time.sleep(5)
    print("the very important people whose impressions of her would affect her career, and, by extension, the rest of her life.")
    time.sleep(4)
    print("She had no time for this, so it was only a moment that she stood there, staring down at the body.")
    time.sleep(3)
    print("And then she turned and ran.")
    time.sleep(5)
    door.door()
    
